<?= $this->partial('/common/header.phtml', $this) ?>

<ol class="breadcrumb">
    <li><a href="/">首頁</a>
    <?php foreach (array_reverse($this->goodid->getParents()) as $parent) { ?>
    <span class="divider">/</span></li>
    <li><a href="/index/goodid/<?= $parent->id ?>"<?= $parent->id == $this->goodid->id ? ' class="active"' : '' ?>><?= $parent->id() ?>.<?= $this->escape($parent->name) ?></a></li>
    <?php } ?>
    </li>
</ol>

<h2>分類</h2>
JSON: <?= $this->partial('/common/link.phtml', array('link' => 'api/goodid/' . $this->goodid->id())) ?>
<ul>
    <?php foreach (GoodId::search(arraY('parent_id' => $this->goodid->id)) as $good_id) { ?>
    <li><a href="/index/goodid/<?= $good_id->id ?>"><?= $good_id->id() ?>. <?= $this->escape($good_id->name) ?></a>
    <?php } ?>
</ul>
