<?= $this->partial('/common/header.phtml', $this) ?>
<h1>資料更新時間</h1>
時間: <?= GoodId::getLatestTime() ?>
<h1>分類</h1>
JSON: <?= $this->partial('/common/link.phtml', array('link' => 'api/goodid/0')) ?>
<ul>
    <?php foreach (GoodId::search(arraY('parent_id' => 0)) as $good_id) { ?>
    <li><a href="/index/goodid/<?= $good_id->id ?>"><?= $good_id->id() ?>. <?= $this->escape($good_id->name) ?></a>
    <?php } ?>
</ul>
